### PR TITLE
Support Enhanced LRC format + additional QOL features (Part I)

### PR DESCRIPTION
**Pull request by Nafeij**
> [Enhanced LRC](https://www.wikiwand.com/en/LRC_(file_format)#Enhanced_format) is an extension of Simple LRC Format developed for the A2 Media Player. This supports adding an optional timestamp for words, syllables, or otherwise parts of a line. It takes the format: `<mm:ss.xx>`.

## Enhanced LRC support

- Add functionality to parse Enhanced LRC
- Add additional interfaces and functions

### 20/4/23

- Add options:
  - `enhanced`: parse entire input as Simple or Enhanced LRC. default false.
  - ~~`strip`: ignore empty lines. default false.~~
- Parser will now support repeating times for Enhanced LRC
  - Will pre-calculate timing offsets for syllables based on the line's start time.
- Added relevant types.

### 25/4/23

- Add functions:
  - `toString`: inverse of `parse`; returns valid lrc for given list of Line objects.
  - `expand`: alias for `toString(parse(lrc: string))`
    The use case for this is to 'unroll' or 'expand' lines with repeat-timestamps into separate lines. This is straightforward to implement as `parse` already does this when building the Lrc list. This is especially useful for Enhanced Lrc as repeating timestamps are not supported by the specification.
- Add playground options to reflect the features listed above.

## Misc

- [Added build command to `prepare` script to support sideloading from git repos](https://stackoverflow.com/questions/40528053/npm-install-and-build-of-forked-github-repo).

This should be backwards-compatible with previous versions.

_Note: This PR is required before merging [Part II](https://github.com/mebtte/react-lrc/pull/8)._

### CODE REVIEW

**Comment by mebtte** [comment]
@Nafeij Thanks for contributing.

Supporting enhanced format is a good idea, but i think it's usage may be less than simple format and compatibility with enhanced format will be slow down `parse` function, so adding a new function like `parseEnhanced` or adding a option like `parse(lrc, { enhanced: true })` is a better choice?

**Comment by mebtte** [comment]
And there is a issue, `[00:32.79][00:56.00]Little <00:33.58>jagged <00:34.14>edge<00:35.25>` should be generate two items, but only one in the result.
image

**Comment by Nafeij** [comment]
@mebtte 

*20/4/23*

- Add options:
  - `enhanced`: parse entire input as Enhanced LRC, instead of Simple LRC. default false.
  - `strip`: ignore empty lines. default false.
- Parser will now support repeating times for Enhanced LRC lines
  - Will pre-calculate timing offsets for syllables based on the line's start time.
- Added relevant types.

**Comment by mebtte** [comment]
I think `strip` is unnecessary and it will make developer confusing with empty line and empty content.

**Comment by mebtte** [comment]
`expand` is verbose and it's unnecessary.

**Comment by mebtte** [comment]
According to [wiki](https://en.wikipedia.org/wiki/LRC_(file_format)#Enhanced_format|Enhanced%20LRC), `word` is better than `syllable `.

**Comment by mebtte** [comment]
Rewrite `parse(lrc, { enhanced: true  })` to `parseEnhanced(lrc)`, it can reuse `parse` and has better typescript return type.

**Comment by mebtte** [comment]
I think `stringify` is better than `toString`.

**Comment by mebtte** [comment]
From the wiki, enhanced lrc format is `[time]<time>content<time>content`, not `[time]content<time>content<time>`.

**Comment by mebtte** [comment]
It seems `stringify` doesn't do much, because array of `Line` is more complex than lrc string itself.

**Pull request merged**
